<?php

return [
    "fr:/fr" => "index",
    "en:/en" => "index",
    "fr:/contactez-nous" => "contactez-nous",
    "en:/contact-us" => "contactez-nous",
    "fr:/contactez-nous/#sujet" => "contactez-nous",
    "en:/contact-us/#sujet" => "contactez-nous",
    "fr:/espace-client" => "espace-client",
    "en:/client-area" => "espace-client",
    "fr:/v4/tableau-de-bord" => "v4/tableau-de-bord",
    "en:/v4/dashbord" => "v4/tableau-de-bord",
    "fr:/v4/tableau-de-bord/#action/#key" => "v4/tableau-de-bord",
    "en:/v4/dashbord/#action/#key" => "v4/tableau-de-bord",
    "fr:/v4/mes-licences" => "v4/mes-licences",
    "en:/v4/my-licenses" => "v4/mes-licences",
    "fr:/v4/mes-facture" => "v4/mes-factures",
    "en:/v4/invoices" => "v4/mes-factures",
    "fr:/v4/mes-factures/#id" => "v4/mes-factures",
    "en:/v4/invoices/#id" => "v4/mes-factures",
    "fr:/v4/boite-a-suggestion" => "v4/boite-a-suggestion",
    "en:/v4/suggestion-box" => "v4/boite-a-suggestion",
    "fr:/v4/votre-profil" => "v4/votre-profil",
    "en:/v4/your-profile" => "v4/votre-profil",
    "fr:/v4/deconnexion" => "v4/deconnexion",
    "en:/v4/logout" => "v4/deconnexion",
    "fr:/admin/gestion-des-clients/#action/#id" => "admin/gestion-des-clients",
    "fr:/admin/gestion-des-licences/#action/#id" => "admin/gestion-des-licences",
    "fr:/admin/gestion-des-suggestions/#action/#id" => "admin/gestion-des-suggestions",
    "fr:/admin/gestion-des-prospects/#action/#id" => "admin/gestion-des-prospects",
    "fr:/admin/gestion-des-demandes/#action/#id" => "admin/gestion-des-demandes",
    "fr:/admin/gestion-des-factures/#action/#id" => "admin/gestion-des-factures",
];
